<a href="https://colab.research.google.com/github/Sashank11/learn_tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we cover fundamental concepts of tensors using tensorflow

Topics covered:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function ( way to speed of py func)
* Using GPUs with TensorFlow (or TPUs)
* Excercises to try yourself


### Introduction to tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check no of dimensions of a tensor with ndim
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check ndim of vector
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dim)
matrix = tf.constant([[10,7],
                     [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 7.],
                               [3.,2.],
                               [8., 9.]], dtype = tf.float16) # Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                        [[7,8,9],
                         [10, 11,12]],
                       [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have learned so far:
* Scalar: A single number
* Vector: A number with direction (e.g wind speed and direction)
* Matrix: A 2-dimensional array of numbers
* Tensor: A n-dimensional array of numbers (n = 0, 1, 2, ......

### Creating tensors with `tf.Variable`

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# changing element of changeable tensor
# changeable_tensor[0] =7 gives error

In [16]:
# Using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# trying for unchangeable tensor
# unchangeable_tensor[0] = 7
# unchangeable_tensor[0].assign(7)
# both give error as tf.constant() tensor can't be changed